name: Context Dump

on: push

jobs:
  context-dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run: | 
          echo ${{ contains( 'Hello', 'll' ) }}
          echo ${{ startswith( 'Hello', 'he' ) }}
          echo ${{ endswith( 'Hello', 'lo' ) }}
          echo ${{ format( 'Hello {0}{1}{2}', 'World', '!', '!' ) }}
          